### ISSUE TITLE
Feature: User Activity Train

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Quiltoni.PixelBot#29]
We shall create a user-activity train that encourages repeated interactions.  This could be a Follower Train, Cheer Train, or a Sub Train.

Some configuration that will be needed:

Counter - current length of train (store in memory)
Timer - maximum duration between action (Channel Config)
Action - what are we tracking to keep the train going (Channel Config)
Appearance - what images, colors do we show for different states of the train (Channel Config)
>>  every X number of actions triggers a different appearance
>>  every X number of actions grants VIP access to the actor
Record - maximum achieve train length and date achieved (Channel Config)

**Comment by jedelfraisse** [comment]
Here is the idea from the live stream on 09/20/19.  The "engine" could have a picture of the broadcaster.  Then as each new follower is detected in the time limit, they can be added to the train as a "car" and have their icon as a sign on the car.  Then after a set amount of time the train would end with a caboose that says "Thank you".

**Comment by Janisku7** [comment]
so if we refactor this feature like so having UserActivityTrain.cs and UserActivityTrain.scss so style sheets as scss so those then use followerTrain cheerTrain, subscriberTrain use UserActivityTrain so having interface like IUserActivityTrain could be one tool to use in this
