### ISSUE TITLE
Add version to the footer

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/Quiltoni.PixelBot#59]
Need to detect the application version and write it in the footer.

Also:  need to set the application version

**Comment by Stelzi79** [comment]
For semi automatic versioning I use [minver](https://github.com/adamralph/minver). It basically uses Git tags to set all the AssemblyVersion, FileVersion, PackageVersion and Version of the project. You add it as a package reference and can set a few things (if needed) in the *.csproj.

> How it works
> When the current commit is tagged with a version, the tag is used as-is.
>
> When the current commit is not tagged, MinVer searches the commit history for the latest tag. If the latest tag found is a pre-release, MinVer will use it as-is. If the latest tag found is RTM (not pre-release), MinVer will add default pre-release identifiers. ... MinVer will also increase the patch number,

I think you then can get these values from the AppDomain and write it there into the footer.

Now I use it in every project I start. See the file [Directory.Build.props](https://github.com/Stelzi79/DotNetTemplate/blob/master/src/Directory.Build.props) that I have in my template repo as a example on how to use it.

**Comment by csharpfritz** [comment]
Added minver to the project.  I feel like this should also appear in the DevOps pipeline and the version number for the container.
